# Generated by Django 4.2 on 2023-05-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="hos_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hos_name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=300)),
                ("date", models.EmailField(max_length=254)),
                ("image", models.ImageField(upload_to="hospital/images")),
            ],
        ),
    ]
