# Generated by Django 4.2 on 2023-05-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_alter_hos_list_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="hos_list",
            name="services",
            field=models.CharField(default="", max_length=300),
        ),
    ]
