# Generated by Django 4.2 on 2023-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0003_hos_list_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hos_list",
            name="desc",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="hos_list",
            name="services",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
