# Generated by Django 4.2 on 2023-05-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0005_hos_list_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="hos_list",
            name="hos_bed",
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
