# Generated by Django 4.2 on 2023-05-05 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0006_hos_list_hos_bed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hos_list",
            old_name="hos_bed",
            new_name="hos_beds",
        ),
    ]
