# Generated by Django 4.2 on 2023-05-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0007_rename_hos_bed_hos_list_hos_beds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hos_list",
            name="hos_beds",
            field=models.IntegerField(default=0),
        ),
    ]
