# Generated by Django 4.2 on 2023-05-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0010_reviews"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="reviews",
            new_name="reviewm",
        ),
    ]
